# image will be published to ghcr.io/<user>/<name>
name: gidro-os
# description will be included in the image's metadata
description: My personalized custom OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: base.yml
  - from-file: module-recipes/files.yml
  - from-file: module-recipes/kargs.yml
  - from-file: module-recipes/dnf.yml
  - from-file: module-recipes/gnome-extensions.yml
  - from-file: module-recipes/justfiles.yml
  #- type: yafti
  - from-file: module-recipes/default-flatpaks.yml
  - from-file: module-recipes/bling.yml
  - from-file: module-recipes/systemd.yml
  - type: gschema-overrides
  - from-file: module-recipes/wallpapers.yml
  - from-file: module-recipes/scripts.yml
  - type: initramfs
  - type: signing
