# image will be published to ghcr.io/<user>/<name>
name: gidro-os
# description will be included in the image's metadata
description: My personalized custom OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: module-recipes/files.yml
  - from-file: module-recipes/xdg-autostart-workaround.yml
  - from-file: module-recipes/akmods.yml 
  - from-file: module-recipes/rpm-ostree.yml
  - from-file: module-recipes/gnome-extensions.yml
  - from-file: module-recipes/notifications-alert.yml
  - from-file: module-recipes/initramfs.yml
  - type: yafti
  - type: brew
    update-interval: '23h' # Optional - Default: '6h' - Expects type: string
    upgrade-interval: '23h' # Optional - Default: '8h' - Expects type: string
    wait-after-boot-update: '250min' # Optional - Default: '10min' - Expects type: string
    wait-after-boot-upgrade: '250min' # Optional - Default: '30min' - Expects type: string
    auto-update: false # Optional - Default: true - Expects type: boolean
    auto-upgrade: false # Optional - Default: true - Expects type: boolean
    nofile-limits: true # Optional - Default: false - Expects type: boolean
    brew-analytics: false # Optional - Default: true - Expects type: boolean
  - from-file: module-recipes/default-flatpaks.yml
  - from-file: module-recipes/bling.yml
  - from-file: module-recipes/systemd.yml
  - from-file: module-recipes/gschema-overrides.yml
  - from-file: module-recipes/scripts.yml
  - from-file: module-recipes/wallpapers.yml  
  - type: signing
