#!/bin/sh
files="$@"

for f in "$files"; do
  if grep -E -q 'github.com/AppImage/AppImageKit/wiki/FUSE' "$f"; then
    chmod a+x "$f"
    mkdir -p "$f.home" "$f.share" "$f.config" "$f.cache"
  fi
done
