type: gnome-extensions
install:
  - nightthemeswitcherromainvigier.fr.v77
  - middleclickclosepaolo.tranquilli.gmail.com.v30
  - Bluetooth-Battery-Metermaniacx.github.com.v14
  - reboottouefiubaygd.com.v20
