type: script
scripts:
  - signing.sh
  - reload-font-cache.sh
  - system76-scheduler.sh
  - system76-power.sh
  - gnome-extensions-uninstall.sh
  - desktop-shortcut-remover.sh
  - vrr.sh
  - hardware-setup.sh
  - proton-ge-updater.sh
  - python3-icoextract.sh
  - morewaita.sh
  - mangohud.sh
