type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/nxmbit/gnome-perf-patched/repo/fedora-%OS_VERSION%/nxmbit-gnome-perf-patched-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/szydell/system76/repo/fedora-%OS_VERSION%/szydell-system76-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/hl2linux-selinux/repo/fedora-%OS_VERSION%/kylegospo-hl2linux-selinux-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/rom-properties/repo/fedora-%OS_VERSION%/kylegospo-rom-properties-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/fiftydinar/gnome-randr-rust/repo/fedora-%OS_VERSION%/fiftydinar-gnome-randr-rust-fedora-%OS_VERSION%.repo

install:
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-system76-scheduler
  - ddccontrol-gtk
  - ddccontrol-db
  - ddccontrol
  - hl2linux-selinux
  - rom-properties-gtk3
  - nautilus-python
  - system76-power
  - python3-icoextract
  - gnome-randr-rust

remove:
  - firefox
  - firefox-langpacks
  - htop
  - nvtop
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-initial-setup
  - gnome-system-monitor
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-classic-session
  - gnome-tweaks
