# image will be published to ghcr.io/<user>/<name>
name: gidro-os
# description will be included in the image's metadata
description: My personalized custom OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-modules/files.yml
  - from-file: common-modules/xdg-autostart-workaround.yml
  #- from-file: common-modules/akmods.yml 
  - from-file: common-modules/rpm-ostree.yml
  - from-file: common-modules/gnome-extensions.yml
  - from-file: common-modules/notifications-alert.yml
  - from-file: common-modules/initramfs.yml
  - type: yafti
  - from-file: common-modules/default-flatpaks.yml
  - from-file: common-modules/bling.yml
  - from-file: common-modules/systemd.yml
  - from-file: common-modules/gschema-overrides.yml
  - from-file: common-modules/scripts.yml
  - from-file: common-modules/wallpapers.yml  
  - type: signing
