# image will be published to ghcr.io/<user>/<name>
name: gidro-os
# description will be included in the image's metadata
description: My personalized custom OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nokmods
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
         - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
         - https://copr.fedorainfracloud.org/coprs/kylegospo/hl2linux-selinux/repo/fedora-%OS_VERSION%/kylegospo-hl2linux-selinux-fedora-%OS_VERSION%.repo
         - https://copr.fedorainfracloud.org/coprs/kylegospo/rom-properties/repo/fedora-%OS_VERSION%/kylegospo-rom-properties-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
         - gnome-shell-extension-caffeine
         - gnome-shell-extension-blur-my-shell
         - gnome-shell-extension-system76-scheduler
         - ddccontrol-gtk
         - ddccontrol-db
         - ddccontrol
         - hl2linux-selinux
         - rom-properties-gtk3
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - htop
      - nvtop
      - gnome-software-rpm-ostree
      - gnome-tour
      - gnome-system-monitor
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-classic-session
      - gnome-tweaks      

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      # - fonts # selection of common good free fonts
      # - justfiles
        # add "!include /usr/share/ublue-os/just/bling.just"
        # in your custom.just (added by default) or local justfile
      # - nix-installer # shell shortcuts for determinate system's nix installers
      # - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti
      # if included, yafti and it's dependencies (pip & libadwaita)
      #  will be installed and set up
    custom-flatpaks:
      # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - reload-font-cache.sh
      - enable-system76-scheduler-service.sh
      - gnome-extensions-uninstall.sh
      - remove-fwupd-testing.sh
      - rom-properties-shortcut-remove.sh
