type: gnome-extensions
install:
  - nightthemeswitcherromainvigier.fr.v75
  - middleclickclosepaolo.tranquilli.gmail.com.v30
  - notifications-alert-on-user-menuhackedbellini.gmail.com.v50
  - Bluetooth-Battery-Metermaniacx.github.com.v14
  - reboottouefiubaygd.com.v20
  - VitalsCoreCoding.com.v67
