type: script
scripts:
  - reload-font-cache.sh
  - system76-scheduler.sh
  - gnome-extensions-uninstall.sh
  - desktop-shortcut-remover.sh
  - proton-ge-updater.sh
  - python3-icoextract.sh
  - morewaita.sh
  - block-ads.sh
  - gnome-locale-flatpak-fix.sh
  - signing.sh
