type: script
scripts:
  - reload-font-cache.sh
  - gnome-extensions-uninstall.sh
  - desktop-shortcut-remover.sh
  - proton-ge-updater.sh
  - python3-icoextract.sh
  - morewaita.sh
  - miniaturo-raw-thumbnailing.sh
  - block-ads.sh
  - zluda.sh
  - binutils-workaround.sh
