type: systemd
system:
  enabled:
    - hardware-setup.service
    - com.system76.PowerDaemon.service
    - system76-power-wake.service
    - com.system76.Scheduler.service
  masked:
    - power-profiles-daemon.service
user:
  enabled:
    - podman.socket
