type: systemd
system:
  enabled:
    - minimum-free-zram.service
    - flatpak-gidro@deluge.service
    - flatpak-gidro@discord.service
    - flatpak-gidro@steam.service
    - flatpak-gidro@telegram.service
    - flatpak-gidro@tutamail.service
