type: systemd
system:
  enabled:
    - minimum-free-zram.service
    - com.system76.PowerDaemon.service
    - system76-power-wake.service
    - com.system76.Scheduler.service
  masked:
    - power-profiles-daemon.service
user:
  enabled:
    - podman.socket
