type: wallpapers
default:
  wallpaper-light-dark:
    - grasssky-bb-light.jxl + grasssky-bb-dark.jxl
scaling:
  scaled: all
  stretched:
    - nordwood-themes-R53t-Tg6J4c-unsplash.jpg
    - Psihovan-bb-light.jpg + Psihovan-bb-dark.jpg
  wallpaper:
    - grasssky-bb-light.jxl + grasssky-bb-dark.jxl
