type: wallpapers
default:
  wallpaper:
    - Black and White Jelly-proteus.png
scaling:
  scaled: all
  stretched:
    - Psihovan-bb-light.jpg + Psihovan-bb-dark.jpg
  wallpaper:
    - Black and White Jelly-proteus.png
